name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior
      value: |
        1. 
        2. 
        3. 
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your system information
      value: |
        - OS: 
        - Compiler: 
        - GPU: 
        - OpenGL Version: 
        - EasyGPU Version/Commit: 
  - type: textarea
    id: code
    attributes:
      label: Code
      description: Minimal code that reproduces the issue
      render: cpp
